### ISSUE TITLE
No errors raised when retry parsing llm response

### ISSUE THREAD

**Issue by Mayazure** [Experts-replaced-by-LLMs/llm_political_analysis#2]
In `analyze_text_with_batch()` [Line 171](https://github.com/Experts-replaced-by-LLMs/llm_political_analysis/blob/c625535b87ad617a6a5d8d1cfcd556765f52d66c/modules/analyze.py#L171), llm response is added to the result dictionary without validation during retries.

**Comment by Mayazure** [comment]
Not sure whether this affects the previous results thus opening this issue.

**Comment by tvashtar** [comment]
Good catch. Yes adding a check here will make it more robust. This won’t invalidate prior runs, it just makes sure the score returned is NA or 1-10. You’d see it in your results if anything else snuck in. Want to add it to your PR and then we should merge that PR
